library(Seurat)
library(SeuratObject)
library(ggplot2)
library(magrittr)
library(dplyr)
library(patchwork)
library(Signac)
library(SingleR)
library(celldex)
library(presto)
library(harmony)
library(multtest)
library(AnnotationHub)
library(ensembldb)
library(glmGamPoi)
library(tidyverse)
library(Matrix)
library(RCurl)
library(scales)
library(cowplot)
library(harmony)
library(knitr)

GSE <- readRDS("/rds/general/user/ph323/ephemeral/GSE131907/GSE131907_Lung_Cancer_normalized_log2TPM_matrix.rds")
GSE <- CreateSeuratObject(counts=GSE, assay="RNA", project="GSE131907")

saveRDS(GSE, "/rds/general/user/ph323/ephemeral/GSE131907/GSE131907.rds")